server:
  port: 8060

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/

zuul:
  routes:
    department:
      path: /department/**
      serviceId: department
    student:
      path: /student/**
      serviceId: student